// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using U3A.Database;

#nullable disable

namespace U3A.Database.Migrations.TenantStoreDb
{
    [DbContext(typeof(TenantStoreDbContext))]
    [Migration("20221125194407_EFCoreStore_Eway")]
    partial class EFCoreStoreEway
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("U3A.Model.TenantInfoEx", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ConnectionString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EwayAPIKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EwayPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identifier")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SendGridAPIKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TwilioAccountSID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TwilioAuthToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TwilioPhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("UseEmailTestEnviroment")
                        .HasColumnType("bit");

                    b.Property<bool>("UseEwayTestEnviroment")
                        .HasColumnType("bit");

                    b.Property<bool>("UseSMSTestEnviroment")
                        .HasColumnType("bit");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Identifier")
                        .IsUnique()
                        .HasFilter("[Identifier] IS NOT NULL");

                    b.ToTable("TenantInfo");

                    b.HasData(
                        new
                        {
                            Id = "9D36C579-9D45-4ACE-8260-7673DBF53572",
                            ConnectionString = "Data Source=tcp:u3admin-server.database.windows.net,1433;Initial Catalog=U3A;User Id=u3admin-server-admin@u3admin-server.database.windows.net;Password=1JYL735FP13D1T1R$",
                            Identifier = "demo",
                            Name = "U3A Demonstration Only",
                            State = "NSW",
                            UseEmailTestEnviroment = false,
                            UseEwayTestEnviroment = false,
                            UseSMSTestEnviroment = false,
                            Website = "https://eastlakes.u3anet.org.au/"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
